In [5]:

import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [6]:
%timeit [j**2 for j in range(1,9)]

561 ns ± 5.63 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
import numpy as np

%timeit np.arange(1,9)**4

2.79 µs ± 19.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#numpy array vs. python lists  

In [2]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
print(y)
print(type(y))
print(type(x))
y

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'list'>


array([1, 2, 3, 4])

# create numpy array

In [3]:
l = []

for i in range(1,5):
    int_1 = input("enter :")
    l.append(int_1)
print(np.array(l))

enter : 12
enter : 15
enter : 17
enter : 18


['12' '15' '17' '18']


In [4]:
#checking the dimension of the array by using the ndim function
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [6]:
# two dimensional array

ar2 = np.array([[1,2,3,4],[6,7,8,9]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [6 7 8 9]]
2


In [7]:
# three dimensional array

ar3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [10]:
#multidimensional array
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# create numpy array using numpy function


In [12]:
#array with zeros

import numpy as np
ar_zero = np.zeros(4)

ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# array with empty

ar_empty = np.empty(6)


print(ar_empty)

[1. 1. 1. 1. 1. 1.]


In [15]:
# array with ones

ar_one = np.ones(4)
ar_one1 = np.ones((3,2))

print(ar_one)
print()
print(ar_one1)


[1. 1. 1. 1.]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
# array with the range of the elements

ar_rn = np.arange(7)
ar_rn1 = np.arange(3,4)
print(ar_rn)
print()
print(ar_rn1)


[0 1 2 3 4 5 6]

[3]


In [23]:
# array with diagonal elements with one

ar_dia = np.eye(5)
ar_dia1 = np.eye(3,5)

print(ar_dia)
print()
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [29]:
#linespace

ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


#creating the numpy array with the numpy function


In [2]:
#creating the numpy array with the numpy function


#rand() fuction is used to generate a random value between 0 and 1

import numpy as np
var = np.random.rand(5)
var1 = np.random.rand(2,5)
print(var)
print()
print(var1)

[0.49561642 0.83273033 0.10454591 0.47294274 0.89763373]

[[0.14407818 0.16538403 0.43936982 0.27306008 0.50899432]
 [0.5650962  0.93334037 0.23011894 0.18039244 0.3416046 ]]


In [3]:
#randn()  function is used to generate a random value of the close to the zero
  # it is either +ve or -ve
var2 = np.random.randn(4)
print(var2)


[-0.6123025   2.08368902  0.71790605  0.56548789]


In [4]:
#ranf()  the function for doing random sampling in numpy.
#it returns an array of specified shape and fills it with random in the half open interval [0.0,1.0)

var3 = np.random.ranf(4)
print(var3)


[0.8461864  0.92103259 0.97444693 0.07902323]


In [6]:
#randint() the function is used to generate a random number on agiven range
#(min,max,total_values)

var4 = np.random.randint(5,20,5)
print(var4)

[13 18 11 13 19]


# data type of the numpy array


In [10]:
# data type of the numpy array

a1 = np.array([1,2,3,4])
print(a1)
print("Data Type :",a1.dtype)
 

[1 2 3 4]
Data Type : int32


In [11]:
a2 = np.array([1.0,2.0,1.3])
print(a2)
print("Data Type : ",a2.dtype)

[1.  2.  1.3]
Data Type :  float64


In [12]:
a3 = np.array(["R","A","V","I"])
print(a3)
print("Data Type :",a3.dtype)

['R' 'A' 'V' 'I']
Data Type : <U1


In [13]:
a4 = np.array(["R","A","V","I",1,4,3])
print(a4)
print("Data Type :",a4.dtype)

['R' 'A' 'V' 'I' '1' '4' '3']
Data Type : <U11


In [18]:
# converting the datatype


a5 = np.array([1,2,3,4])
a5i = np.array([1,2,3,4],dtype = np.int8 )
print(a5)
print("Data Type :",a5.dtype)
print()
print(a5i)
print("Data Type :",a5i.dtype)


[1 2 3 4]
Data Type : int32

[1 2 3 4]
Data Type : int8


In [20]:
a6 = np.array([1,2,3,4])
print(a6)
print("DataType :",a6.dtype)

print()

a6i = np.array([1,2,3,4],dtype = "f")
print(a6i)
print("Data Type :",a6i.dtype)

[1 2 3 4]
DataType : int32

[1. 2. 3. 4.]
Data Type : float32


In [24]:
a7 = np.array([1,2,3,4])
print(a7)
print("Data Type :",a7.dtype)

print()

a7i = np.float32(a7)
print(a7i)
print("Data Type :",a7i.dtype)
print()

a7ii = np.int_(a7i)
print(a7ii)
print("Data Type :",a7ii.dtype)


[1 2 3 4]
Data Type : int32

[1. 2. 3. 4.]
Data Type : float32

[1 2 3 4]
Data Type : int32


In [25]:
a8 = np.array([1,2,3,4])
print(a8)
print("Data Type :",a8.dtype)

print()

a8i = a8.astype(float)
print(a8i)
print("Data Type :",a8i.dtype)


[1 2 3 4]
Data Type : int32

[1. 2. 3. 4.]
Data Type : float64


#LEARN BROADCASTING IN NUMPY ARRAYS.....


#dimension calculation in order to perform arthemtic operation

In [2]:
# wantedly error 

import numpy as np



b1 = np.array([1,2,3,4])
b2 = np.array([1,2,3,4])

b3 = b1 + b2
print(b3)

[2 4 6 8]


In [6]:
# 1.same Dimension
import numpy as np

b4 = np.array([1,2,3,4])
print(b4)

print()

print(b4.shape)

print()

b5 = np.array([[1],[2],[3]])
print(b5)

print()

print(b5.shape)

print()

print(b4 + b5)

[1 2 3 4]

(4,)

[[1]
 [2]
 [3]]

(3, 1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [7]:
b6 = np.array([[1],[2]])
print(b6)

print()

print(b6.shape)

print()

b7 = np.array([[1,2,3],[1,2,3]])
print(b7)

print()

print(b7.shape)

print(b6 + b7)

[[1]
 [2]]

(2, 1)

[[1 2 3]
 [1 2 3]]

(2, 3)
[[2 3 4]
 [3 4 5]]


#indexing and slicing in numpy array...



In [10]:
#indexing......
#One dimensional array indexing...

import numpy as np
d = np.array([9,8,7,6])
print(d)

print()


print(d[1])

print()

print(d[-2])


[9 8 7 6]

8

7


In [12]:
#Two dimensional array indexing...

di = np.array([[1,2,3,4],[4,5,6,7]])
print(di)

print()

print(di.ndim)

print()

print(di[0,3])



[[1 2 3 4]
 [4 5 6 7]]

2

4


In [16]:
#Three dimension array indexing...

dii = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(dii)

print()

print("Dimension :",dii.ndim)

print()

print(dii[0,1,1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

Dimension : 3

5


In [24]:
#Slicing numpy array...

#one dimensoinal array slicing..

diii = np.array([1,2,3,4,5,6,7,8,9])
print(diii)

print()

print("Slicing - 2 to 5 :",diii[1:4])

print()

print("Slicing 2 to end :",diii[1:])

print()

print("Start to 5       :",diii[:6])

print()

print("Steping          :",diii[::2])

[1 2 3 4 5 6 7 8 9]

Slicing - 2 to 5 : [2 3 4]

Slicing 2 to end : [2 3 4 5 6 7 8 9]

Start to 5       : [1 2 3 4 5 6]

Steping          : [1 3 5 7 9]


In [27]:
#Two dimensional array slicing...

diiii = np.array([[1,2,3,4],[6,7,8,9],[11,12,13,14]])
print(diiii)

print()

print("Dimension    :",diiii.ndim)

print()

print('Slicing      :',diiii[0,1:])

print()

print("Slicing      :",diiii[2,1:])


[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]

Dimension    : 2

Slicing      : [2 3 4]

Slicing      : [12 13 14]


#ITERATING THE NUNMPY ARRAAY...



In [1]:

# One Dimensional array iterating...

import numpy as np
x = np.array([1,2,3,4,5,6])

print(x)

print()

for i in x:
    print(i)


[1 2 3 4 5 6]

1
2
3
4
5
6


In [3]:
# Two Dimensional array iterating...

xi = np.array([[1,2,3,4],[6,7,8,9]])
print(xi)

print()

for j in xi:
    print(j)

print()

for k in xi:
    for l in k:
        print(l)

[[1 2 3 4]
 [6 7 8 9]]

[1 2 3 4]
[6 7 8 9]

1
2
3
4
6
7
8
9


In [5]:
# Three Dimensional array iterating...

xii = np.array([[[1,2,3,4],[6,7,8,9]]])

print(xii)

print()

print("Dimension   :",xii.ndim)

print()

for i in xii:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [6 7 8 9]]]

Dimension   : 3

1
2
3
4
6
7
8
9


In [7]:

xiii = np.array([[[1,2,3,4],[5,6,7,8]]])
print(xiii)

print()

print("Dimension  :",xiii.ndim)

print()

for i in np.nditer(xiii):
    print(i)


[[[1 2 3 4]
  [5 6 7 8]]]

Dimension  : 3

1
2
3
4
5
6
7
8


In [26]:
import numpy as np

xiiii = np.array([[[9,8,7,6],[1,2,3,4]]])
print(xiiii)

print() 

for j in np.nditer(xiiii):
    print(j)

print()

for i in np.ndenumerate(xiiii):
    print(i)

print()

for k,d in np.ndenumerate(xiiii):
    print(k,d)


[[[9 8 7 6]
  [1 2 3 4]]]

9
8
7
6
1
2
3
4

((0, 0, 0), 9)
((0, 0, 1), 8)
((0, 0, 2), 7)
((0, 0, 3), 6)
((0, 1, 0), 1)
((0, 1, 1), 2)
((0, 1, 2), 3)
((0, 1, 3), 4)

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


#COPY VS VIEW IN NUMPY PYTHON ARRAY...


In [28]:
#  copy() function...

import numpy as np

y = np.array([1,2,3,4])

print(y)

print()

co = y.copy()
print("COPY  :",co)

[1 2 3 4]

COPY  : [1 2 3 4]


In [32]:
#  copy() function...
# changes made in original doesnot effect the copy array...

import numpy as np

y = np.array([1,2,3,4])

print(y)

print()

co = y.copy()
print("COPY  :",co)

print()

y[1] = 55
print("Original :",y)

print()

print("COPY      :",co)



[1 2 3 4]

COPY  : [1 2 3 4]

Original : [ 1 55  3  4]

COPY      : [1 2 3 4]


In [29]:
# view() function...

yi = np.array([1,2,3,4])
print(yi)

print()

vi = yi.view()
print("VIEW   :",vi)


[1 2 3 4]

VIEW   : [1 2 3 4]


In [33]:
# view() function
#changes in the original array effects the view array...

yi = np.array([1,2,3,4])
print(yi)

print()

vi = yi.view()
print("VIEW   :",vi)

print()

yi[1] = 69

print("Original array   : ",yi)

print()

print("VIEW array       :",vi)

[1 2 3 4]

VIEW   : [1 2 3 4]

Original array   :  [ 1 69  3  4]

VIEW array       : [ 1 69  3  4]


# JOINING AND SPLIT NUMPY ARRAY


In [40]:
# join array

import numpy as np

j = np.array([1,2,3,4,5])
print(j)

print()

ji = np.array([9,8,7,6])
print(ji)

print()

jj = np.concatenate((j,ji))
print(jj)

[1 2 3 4 5]

[9 8 7 6]

[1 2 3 4 5 9 8 7 6]


In [46]:
# joining the two dimensional array

jii = np.array([[1,2,3,4],[5,6,7,8]])
print(jii)

print()

print("Dimension   :",jii.ndim)

print()

jiii = np.array([[11,12,13,14],[15,16,17,18]])
print(jiii)

print()

print("Dimension   :",jiii.ndim)

print()

jr = np.concatenate((jii,jiii),axis=0)
print(jr)

print()

print(jr.ndim)

print()

jri = np.concatenate((jii,jiii),axis=1)
print(jri)

print()

print(jri.ndim)

[[1 2 3 4]
 [5 6 7 8]]

Dimension   : 2

[[11 12 13 14]
 [15 16 17 18]]

Dimension   : 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]
 [15 16 17 18]]

2

[[ 1  2  3  4 11 12 13 14]
 [ 5  6  7  8 15 16 17 18]]

2


In [53]:
#stack()

s = np.array([[1,2,3,4],[6,7,8,9]])
print(s)

print()

si = np.array([[11,12,13,14],[16,17,18,19]])
print(si)

print()

ss = np.stack((s,si),axis=0)
print(ss)

[[1 2 3 4]
 [6 7 8 9]]

[[11 12 13 14]
 [16 17 18 19]]

[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[11 12 13 14]
  [16 17 18 19]]]


In [54]:
#stack()

s = np.array([[1,2,3,4],[6,7,8,9]])
print(s)

print()

si = np.array([[11,12,13,14],[16,17,18,19]])
print(si)

print()

ss = np.stack((s,si),axis=1)
print(ss)

[[1 2 3 4]
 [6 7 8 9]]

[[11 12 13 14]
 [16 17 18 19]]

[[[ 1  2  3  4]
  [11 12 13 14]]

 [[ 6  7  8  9]
  [16 17 18 19]]]


In [57]:
#stack()

s = np.array([[1,2,3,4],[6,7,8,9]])
print(s)

print()

si = np.array([[11,12,13,14],[16,17,18,19]])
print(si)

print()

ss = np.dstack((s,si))#height
print(ss)

print()

ssi = np.hstack((s,si))#row
print(ssi)

print()


ssii = np.vstack((s,si))#coloumn
print(ssii)

[[1 2 3 4]
 [6 7 8 9]]

[[11 12 13 14]
 [16 17 18 19]]

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]]]

[[ 1  2  3  4 11 12 13 14]
 [ 6  7  8  9 16 17 18 19]]

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


In [61]:
#split array...

import numpy as np

z = np.array([1,2,3,4,5,6,7,8,9])
print(z)

print()

zr = np.array_split(z,3)
print(zr)
print(type(zr))

print()

print(zr[1])


[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>

[4 5 6]


In [67]:
zi = np.array([[1,2,3,4],[6,7,8,9]])

print(zi)

print()

zir = np.array_split(zi,3)
print(zir)

print()

ziri = np.array_split(zi,3,axis=1)
print(ziri)

print()

zirii = np.array_split(zi,3,axis=0)
print(zirii)


[[1 2 3 4]
 [6 7 8 9]]

[array([[1, 2, 3, 4]]), array([[6, 7, 8, 9]]), array([], shape=(0, 4), dtype=int32)]

[array([[1, 2],
       [6, 7]]), array([[3],
       [8]]), array([[4],
       [9]])]

[array([[1, 2, 3, 4]]), array([[6, 7, 8, 9]]), array([], shape=(0, 4), dtype=int32)]



# NUMPY ARRAY FUNCTION()...


In [7]:
# Search array : Search an array for a cerrtain value,and return the indexes that get a match

import numpy as np
var = np.array([1,2,3,4,5,6,5,4,3,8])
print(var)

print()

print("Dimension    :",var.ndim)

print()

x = np.where(var == 2)
print(x)

print()

xi = np.where(var == 4)
print(xi)

print()

xii = np.where((var%2) == 0)
print(xii)

[1 2 3 4 5 6 5 4 3 8]

Dimension    : 1

(array([1], dtype=int64),)

(array([3, 7], dtype=int64),)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [2]:


# Search Sorted Array : which performs a binary search in the array , and returns the index
#                      where the thenspecified value would be inserted to maintain the
#                       the search order...

import numpy as np

var1 = np.array([1,2,3,4,5,8])
print(var1)

print()

v = np.searchsorted(var1,6)
print(v)

print()

vi = np.searchsorted(var1,[6,7])
print(vi)

[1 2 3 4 5 8]

5

[5 5]


In [5]:
# Sort array  : Ordered sequence is any sequence that has an order corresponding to
#               elements ,like numeric or alphabetical,ascending or descending

import numpy as np
var = np.array([1,2,3,4,5,4,3,2,4,5,3,4])
print(var)

print()

print(np.sort(var))

print()

var_1 = np.array(["a","s","i","o","u"])
print(var_1)

print()

print(np.sort(var_1))

[1 2 3 4 5 4 3 2 4 5 3 4]

[1 2 2 3 3 3 4 4 4 4 5 5]

['a' 's' 'i' 'o' 'u']

['a' 'i' 'o' 's' 'u']


In [6]:
# Two dimensinal array sorting..
var_2 = np.array([[3,2,1],[9,8,7],[6,7,5]])
print(var_2)

print()

print(np.sort(var_2))

[[3 2 1]
 [9 8 7]
 [6 7 5]]

[[1 2 3]
 [7 8 9]
 [5 6 7]]


In [8]:
# Filter array  : Getting some elements out of an existing array and
#                 creating a new array out of them...

f = np.array([1,2,3,4,5,4])
print(f)

print()

fi = [True,False,True,False,True,False]
print(fi)

print()

new_f = f[fi]
print(new_f)

print()

print(type(new_f))

[1 2 3 4 5 4]

[True, False, True, False, True, False]

[1 3 5]

<class 'numpy.ndarray'>




# NUMPY ARRAY FUNCTIONS (PART- B)


In [9]:

#np.random.shuffle()

import numpy as np

var = np.array([1,2,3,4,5])
print(var)

print()

np.random.shuffle(var)
print(var)

[1 2 3 4 5]

[1 4 2 5 3]


In [13]:
#np.unique()

var1 = np.array([1,2,3,4,5,6,5,4,3,2])
print(var1)

print()

var1_x = np.unique(var1)
print(var1_x)

print()

var1_xi = np.unique(var1,return_index=True)
print(var1_xi)


print()

var1_xii = np.unique(var1,return_index=True,return_counts=True)
print(var1_xii)

[1 2 3 4 5 6 5 4 3 2]

[1 2 3 4 5 6]

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5], dtype=int64))

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5], dtype=int64), array([1, 2, 2, 2, 2, 1], dtype=int64))


In [15]:
#np.resize(var(2,3))
# converts the one dimensional array to two dimensional array

var = np.array([1,2,3,4,5])
print(var)

print()

y = np.resize(var,(2,3))
print(y)


print()

yi = np.resize(var,(3,2))
print(yi)

[1 2 3 4 5]

[[1 2 3]
 [4 5 1]]

[[1 2]
 [3 4]
 [5 1]]


In [21]:

#flatten is used to arange the order

var = np.array([1,2,3,4,5])
print(var)

print()

y = np.resize(var,(2,3))
print(y)


print()

print("Flatten  :",var.flatten(order="F"))

print()

print("Flatten   :",y.flatten(order="F"))

print()

[1 2 3 4 5]

[[1 2 3]
 [4 5 1]]

Flatten  : [1 2 3 4 5]

Flatten   : [1 4 2 5 3 1]



In [23]:

#Ravel is used for the arranging the order

var = np.array([1,2,3,4,5])
print(var)

print()

y = np.resize(var,(2,3))
print(y)


print()

print("Ravel   :",var.ravel(order="F"))

print()

print("Ravel    :",var.ravel(order="C"))

print()

[1 2 3 4 5]

[[1 2 3]
 [4 5 1]]

Ravel   : [1 2 3 4 5]

Ravel    : [1 2 3 4 5]

