NUMPY

NumPy (Numerical Python) is a powerful Python library used for working with arrays and numerical computations

Arrays:   NumPy provides an array object called ndarray. Unlike Python lists, NumPy arrays             are stored in a continuous memory location, making them faster and more efficient            for numerical operations.

numpy is a general purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays . It is the fundamental package for scientific computing with python


What is an array?
An array is a data structure that stores values of same data type.In Python ,this is the main difference between arrrays and lists. While Python lists can contain values corresponding to different data types , arrays in python can only contain values corresponding to same data type

In [3]:
## initially lets import numpy

import numpy as np
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
'''
shape() function is specify the how many no. of rows and how many no. of columns present in the given array

'''
print(arr.shape)

(5,)


In [11]:
## multidimension array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,8,7,6,5]

arr1 = np.array([my_lst1,my_lst2,my_lst3])

print(arr1)

print()

print(arr1.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 8 7 6 5]]

(3, 5)


In [16]:
'''
reshape() function is used to change the dimension of the arrray
return an array with same elements but different shape
'''
print(arr1.reshape(5,3))

print()

print(arr1.shape)

print()

print(arr1.reshape(1,15))

[[1 2 3]
 [4 5 2]
 [3 4 5]
 [6 9 8]
 [7 6 5]]

(3, 5)

[[1 2 3 4 5 2 3 4 5 6 9 8 7 6 5]]


INDEXING

In [18]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])
print(arr2)

print()

print(arr2[3])

[1 2 3 4 5 6 7 8 9]

4


In [21]:
## multidimension array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,8,7,6,5]

arr1 = np.array([my_lst1,my_lst2,my_lst3])
print(arr1)

print()

print(arr1[0:2,0:2])

print()

print(arr1[1:,3:])

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 8 7 6 5]]

[[1 2]
 [2 3]]

[[5 6]
 [6 5]]


In [23]:
'''
arange() function is used to return evenly spaced values within a given interval
'''
arr3 = np.arange(0,10,2)
#                (start,stop,step)
print(arr3)

[0 2 4 6 8]


In [24]:
'''
linspace() function is used to divide the equal space between two no.
'''
arr4 = np.linspace(1,10,50)
print(arr4)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [27]:
'''
broadcasting()
'''

arr5 = np.array([1,2,3,4,5,6,7,8,9])
print(arr5)

print()

arr5[3:]=100
print(arr5)



[1 2 3 4 5 6 7 8 9]

[  1   2   3 100 100 100 100 100 100]


In [32]:
# some conditions were used to data analysis
arr6 = np.array([1,2,3,4,5,6,7,8,9])
print(arr6)

print()

print(arr6*2)

print()

print(arr6/2)

print()

val = 4
print(arr6<4)

print()

print(arr6[arr6<5])

[1 2 3 4 5 6 7 8 9]

[ 2  4  6  8 10 12 14 16 18]

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]

[ True  True  True False False False False False False]

[1 2 3 4]


In [42]:
'''
Create arrays and reshape

'''
arr8 = np.arange(0,10).reshape(5,2)
print(arr8)

print()

arr7 = np.arange(0,10).reshape(2,5)
print(arr7)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [44]:
arr9 = np.ones(6)
print(arr9)

print()

arr_1 = np.ones((2,5),dtype=int)
print(arr_1)

[1. 1. 1. 1. 1. 1.]

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [45]:
arr_2 = np.random.rand(3,3)
print(arr_2)

[[0.15600605 0.81875126 0.20274265]
 [0.4739375  0.71479049 0.10518433]
 [0.94319441 0.96467543 0.60026188]]


In [46]:
arr_3 = np.random.randn(4,4)
print(arr_3)

[[ 0.04951241  0.49607978  0.33338479  0.80969369]
 [ 1.31702554  0.30527959  1.93092942 -2.13345328]
 [ 0.16792886 -0.16426916  1.46758371 -0.02204059]
 [-0.91415034 -0.70030602  0.20117614  0.24416314]]
