# numpy arithematic operations


In [1]:
# numpy arithematic operations

#ADD

import numpy as np

a1 = np.array([1,2,3,4])
print(a1)

print()

a1i = a1 + 3
print(a1i)


[1 2 3 4]

[4 5 6 7]


In [3]:

#SUBTARCT

import numpy as np

a2 = np.array([1,2,3,4])
print(a2)

print()

a1i = a2 - 3
print(a1i)

[1 2 3 4]

[-2 -1  0  1]


In [4]:

# MULTIPLY

import numpy as np

a3 = np.array([1,2,3,4])
print(a3)

print()

a1i = a3 * 3
print(a1i)

[1 2 3 4]

[ 3  6  9 12]


In [5]:
# DIVIDE

a4 = np.array([1,2,3,4])
print(a4)
print("Data Type :",a4.dtype)

print()

a4i = a4 / 3
print(a4i)
print("Data Type :",a4i.dtype)

[1 2 3 4]
Data Type : int32

[0.33333333 0.66666667 1.         1.33333333]
Data Type : float64


In [6]:
a5 = np.array([1,2,3,4])
print(a5)

print()

a5i = a5 % 3
print(a5i)

[1 2 3 4]

[1 2 0 1]


In [11]:
a6i = np.array([1,2,3,4])
a6ii = np.array([6,7,8,9])
print(a6i)
print(a6ii)
print()

a6iii = a6i + a6ii
print(a6iii)

print()

a6iiii = a6i - a6ii
print(a6iiii)
print()

a6iiiii = np.add(a6i,a6ii)
print(a6iiiii)



[1 2 3 4]
[6 7 8 9]

[ 7  9 11 13]

[-5 -5 -5 -5]

[ 7  9 11 13]


In [13]:
a7 = np.array([[1,2,3,4],[4,5,6,7]])
print(a7)

print()

a7i = np.array([[4,5,6,7],[1,2,3,4]])
print(a7i)

print()

a7ii = a7 + a7i
print(a7ii)

print()

a7iii = a7 - a7i
print(a7iii)

[[1 2 3 4]
 [4 5 6 7]]

[[4 5 6 7]
 [1 2 3 4]]

[[ 5  7  9 11]
 [ 5  7  9 11]]

[[-3 -3 -3 -3]
 [ 3  3  3  3]]


In [14]:
a8 = np.array([1,2,3,4])
print(a8)

print()

a8i = np.reciprocal(a8)

print(a8i)

[1 2 3 4]

[1 0 0 0]


#arithematic functions in numpy arrays.....



In [8]:
 import numpy as np 

b1 = np.array([1,4,6,7,4,9,3,7,66])
print(b1)
print()

#finding the maximum in the given array
print("MAX :",np.max(b1))

print()

#finding the minimum in the given array
print("MIN :",np.min(b1))

print()

#finding the position of the maximum and minimum value of the array
print("MAX :",np.max(b1),"  POSITION :",np.argmax(b1))

print()

print("MIN :",np.min(b1),"   POSITION :",np.argmin(b1))

print()

#sqrt in numpy 

print("SQRT :",np.sqrt(b1))


[ 1  4  6  7  4  9  3  7 66]

MAX : 66

MIN : 1

MAX : 66   POSITION : 8

MIN : 1    POSITION : 0

SQRT : [1.         2.         2.44948974 2.64575131 2.         3.
 1.73205081 2.64575131 8.1240384 ]


In [11]:
b2 = np.array([[4,5,6,7],[1,5,3,4]])
print(b2)

print()

print(np.min(b2,axis=1))

print()

print(np.min(b2,axis=0))





[[4 5 6 7]
 [1 5 3 4]]

[4 1]

[1 5 3 4]


In [10]:
#trigonometry in the numpy

b3 = np.array([1,2,3,4,5])

print(np.sin(b3))

print()

print(np.cos(b3))

print()

# the cumsum() fuction is just like the fibonanci sequence
print(np.cumsum(b3))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]

[ 1  3  6 10 15]


#shape and reshaping i the numpy array


In [15]:
c1 = np.array([[1,2],[6,7]])
print(c1)

print()

print(c1.shape)

print()

c2 = np.array([[1,2,3,4],[5,6,7,8]])
print(c2)

print()

print(c2.shape)

[[1 2]
 [6 7]]

(2, 2)

[[1 2 3 4]
 [5 6 7 8]]

(2, 4)


In [18]:
c3 = np.array([1,2,3,4],ndmin = 5)
print(c3)

print()

print(c3.ndim)

print()

print(c3.shape)

[[[[[1 2 3 4]]]]]

5

(1, 1, 1, 1, 4)


In [ ]:
#reshape

In [22]:
# reshaping the one dimendion to two dimension

c4 = np.array([1,2,3,4,5,6])
print(c4)
print(c4.ndim)

print()

#c5 = c4.reshape(3,2)
# 3 --> 3 refers to the no. of rows
# 2 --> 2 refers to the no. of elements in the one row

c5 = c4.reshape(3,2)
print(c5)
print(c5.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [30]:
#reshaping the one dimension to three dimension

c6 = np.array([1,2,3,4,5,6,7,8,9,12,13,14])
print(c6)
print(c6.ndim)

print()

#c5 = c4.reshape(2,3,2)
# 2 --> 3 refers to the no. of rows
# 3 --> 2 refers to the no. of elements in the one row
# 2 --> 2 refers to the
c7 = c6.reshape(2,3,2)
print(c7)
print(c7.ndim)

print()

# three dimension to one dimension

c8 = c7.reshape(-1)
print(c8)
print(c8.ndim)

[ 1  2  3  4  5  6  7  8  9 12 13 14]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 12]
  [13 14]]]
3

[ 1  2  3  4  5  6  7  8  9 12 13 14]
1


#numpy insert and delete array dunction...


In [13]:
# insert 

import numpy as np

var = np.array([1,2,3,4,5])
print(var)

print()

print(type(var))

print()

v= np.insert(var, 2, 40)
#           (var,index value to insert the value,value)
print(v)

print()

# by using the append(function)

x = np.append(var,6.5)
print(x)

[1 2 3 4 5]

<class 'numpy.ndarray'>

[ 1  2 40  3  4  5]

[1.  2.  3.  4.  5.  6.5]


In [14]:
#Two dimensional array...

var1 = np.array([[1,2,3],[6,7,8]])
print(var1)

print()

print(var1.ndim)

print()

v1 = np.insert(var1 , 2 , [22,23],axis=1)
print(v1)


print()

v2 = np.insert(var1 , 2 , [22],axis=0)
print(v2)

print()

# by using the append() function

x = np.append(var1,[[45,44,43]],axis=0)
print(x)

[[1 2 3]
 [6 7 8]]

2

[[ 1  2 22  3]
 [ 6  7 23  8]]

[[ 1  2  3]
 [ 6  7  8]
 [22 22 22]]

[[ 1  2  3]
 [ 6  7  8]
 [45 44 43]]


In [ ]:
# delete

In [15]:
import numpy as np

var1 = np.array([1,2,3,4,5])
print(var1)

print()

d = np.delete(var1,2)
#             (var,index value )
print(d)

[1 2 3 4 5]

[1 2 4 5]


# THE CONCEPT OF MATRIX NUMPY ARRAY IN PYTHON...


In [4]:
# Matrix in numpy arrays...

# Create matrix in numpy...

import numpy as np

var = np.matrix([[1,2,3,],[1,2,3]])
print(var)

print()

print(type(var))

var1 = np.array([[1,2,3],[1,2,3]])
print(var1)

print()

print(type(var1))

[[1 2 3]
 [1 2 3]]

<class 'numpy.matrix'>
[[1 2 3]
 [1 2 3]]

<class 'numpy.ndarray'>


In [12]:
#Addition of the two matrices...

a = np.matrix([[1,2,3],[1,2,3]])
print(a)

print()

a1 = np.matrix([[1,2,3],[1,2,3]])
print(a1)

print()

print(a + a1)

[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]]

[[2 4 6]
 [2 4 6]]


In [16]:
# Multiplcation of the two matrices...

a = np.matrix([[1,2],[1,2]])
print(a)

print()

a1 = np.matrix([[1,3],[1,2]])
print(a1)

print()

# Matrix calculation
print(a.dot(a1))

print()

#Array calculation
print(a * a)

[[1 2]
 [1 2]]

[[1 3]
 [1 2]]

[[3 7]
 [3 7]]

[[3 6]
 [3 6]]


In [ ]:
# Matrix function in numpay arrays

In [19]:
# Transpose...

import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)

print()

print(np.transpose(var))

print()

print(var.T)


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [23]:
# Swapaxes ...

import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)

print()

print(np.swapaxes(var,0,1))
#                 (var,axis=0,axis=1)



[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [24]:
# Square matrix swapaxes...

var2 = np.matrix([[1,2],[3,4]])
print(var2)

print()

print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [25]:
# Inverse...


var3 = np.matrix([[1,2],[3,4]])
print(var3)

print()

print(np.linalg.inv(var3))


[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:
# power...

# np.linalg.matrix_power(var,n)...

# three conditions for n

# i) n = 0 :- Identity matrix...
# ii) n > 0 :- Power(multiply)...
# iii) n < 0 :- Inversion * power...


var4 = np.matrix([[1,2],[3,4]])
print(var4)

print()

print(np.linalg.matrix_power(var4,0))


print()

print(np.linalg.matrix_power(var4,2))


print()

print(np.linalg.matrix_power(var4,-2))


[[1 2]
 [3 4]]

[[1 0]
 [0 1]]

[[ 7 10]
 [15 22]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [42]:
# Deteminant...


var5 = np.matrix([[1,2],[3,4]])
print(var5)

print()

print(np.linalg.det(var5))


[[1 2]
 [3 4]]

-2.0000000000000004
